name: super fly and really cool fly.io api deploy

on:
  push:
    branches: ["main", "deploy"]
env:
  FLY_API_TOKEN: ${{ secrets.FLYCTL_AUTH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: cd src/api && pwd && ls
    - run: pwd && ls
    - run: flyctl deploy --remote-only
